development:
  adapter: postgresql
  database: bike_warehouse_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bike_warehouse_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bike_warehouse_production
  pool: 5
  timeout: 5000
