development:
  adapter: postgresql
  database: bike_warehouse_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bike_warehouse_test
  pool: 5
  timeout: 5000


production:
  <<: *default
  database: bike_warehouse_production
  username: bike_warehouse
  password: <%= ENV['BIKE_WAREHOUSE_DATABASE_PASSWORD'] %>
  
